[blacklisted-usernames]
blacklist = [
  'itineris',
]

[blacklisted-user-emails]
blacklist = [
  'hello@itineris.co.uk',
]

# This is experimental!
[extra-expected-status-codes]
enabled = false # Enable if needed

[extra-required-constants]
includes = [
  # Gravity Forms.
  # https://docs.gravityforms.com/wp-config-options/
  'GF_LICENSE_KEY',
  'GF_THEME_IMPORT_FILE',
  'GF_RECAPTCHA_PUBLIC_KEY',
  'GF_RECAPTCHA_PRIVATE_KEY',

  # Documents not found.
  'GF_DISABLE_CSS',
  'GF_OUTPUT_HTML5',

  # https://docs.gravityforms.com/gform_disable_auto_update-constant/
  'GFORM_DISABLE_AUTO_UPDATE',

  # WP Migrate DB Pro.
  # https://deliciousbrains.com/wp-migrate-db-pro/doc/activating-license/
  'WPMDB_LICENCE',

  # WP Offload S3.
  # https://deliciousbrains.com/wp-offload-s3/doc/activating-your-license/
  'AS3_CFPRO_LICENCE',

  # https://deliciousbrains.com/wp-offload-s3/doc/quick-start-guide/#save-access-keys
  'AS3CF_AWS_ACCESS_KEY_ID',
  'AS3CF_AWS_SECRET_ACCESS_KEY',

  # https://deliciousbrains.com/wp-offload-s3/doc/settings-constants/
  'WPOS3_SETTINGS',
]

[extra-required-packages]
enabled = false

[extra-required-plugins]
includes = [
  'advanced-custom-fields-pro',
  'bb-plugin',
  'bb-theme-builder',
  'gravity-forms',
  'iwp-client',
  'redirection',
  'uk-cookie-consent',
  'wordpress-seo',
  'wp-offload-s3',
]

[inactive-plugins]
excludes = [
  'password-protected',
]

[itineris-required-caching-plugin]
includes = [
  'kinsta-mu-plugins',
  'w3-total-cache',
]
